<a href="https://colab.research.google.com/github/ssook1222/Data-Analysis-Crush/blob/main/1%ED%9A%8C%EB%8F%85/%EC%A0%84%EC%B2%98%EB%A6%AC/pre_process_102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv', encoding= 'euc-kr')
df

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.50
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.50
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.40
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.40
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

---

### Question 11.
수치형 변수를 가진 컬럼을 출력하라.

In [10]:
cols = list(df.columns)

for col in cols:
  if df[col].dtype != 'object':
    print(col)

id
거주인구
근무인구
방문인구
총 유동인구
평균 속도
평균 소요 시간
평균 기온
일강수량
평균 풍속

### Question 12.
범주형 변수를 가진 컬럼을 출력하라.

In [11]:
cols = list(df.columns)

for col in cols:
  if df[col].dtype == 'object':
    print(col)

일자
시도명
읍면동명

### Question 13.
각 컬럼의 결측치 숫자를 파악하라.

In [24]:
df.isna().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

### Question 14.
각 컬럼의 데이터 수, 데이터 타입을 한 번에 확인하라.

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

### [!] Question 15.
각 수치형 변수의 분포(사분위, 평균, 표준편차, 최대, 최소)를 출력하라.

In [35]:
df.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

### Question 16.
거주인구 컬럼의 값들을 출력하라.

In [36]:
df['거주인구']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

### Question 17.
평균 속도 컬럼의 4분위 범위(IQR) 값을 구하여라.

In [42]:
df['평균 속도'].quantile(q=0.75) - df['평균 속도'].quantile(q=0.25)

14.854999999999997

### Question 18.
읍면동명 컬럼의 유일값 개수를 출력하라.

In [47]:
df['읍면동명'].unique().size

41

### Question 19.
읍면동 컬럼의 유일값을 모두 출력하라.

In [48]:
names = list(df['읍면동명'].unique())

for name in names:
  print(name)

도두동
외도동
이도2동
일도1동
대천동
서홍동
한경면
송산동
조천읍
일도2동
영천동
예래동
대륜동
삼도1동
이호동
건입동
중앙동
삼양동
삼도2동
이도1동
남원읍
대정읍
정방동
효돈동
아라동
한림읍
구좌읍
용담1동
오라동
화북동
연동
표선면
중문동
성산읍
안덕면
천지동
노형동
동홍동
용담2동
봉개동
애월읍

## 02. Filtering & Sorting

### Question 20.
데이터를 로드하라.

In [49]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75